In [ ]:
pip install torch

In [ ]:
pip install transformers

     |████████████████████████████████| 2.5MB 7.5MB/s 
     |████████████████████████████████| 901kB 52.8MB/s 
     |████████████████████████████████| 3.3MB 49.4MB/s 


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
%matplotlib inline

In [ ]:
with open('/content/mahabharath_4chapters_combined.txt','r') as f:
  text = f.read().split('.')

In [ ]:
text = [sent.replace('\n','') for sent in text]

In [ ]:
text[:10]

['Om! Having bowed down to Narayana and Nara, the most exalted male being,and also to the goddess Saraswati, must the word Jaya be uttered',
 "Ugrasrava, the son of Lomaharshana, surnamed Sauti, well-versed in thePuranas, bending with humility, one day approached the great sages ofrigid vows, sitting at their ease, who had attended the twelve years'sacrifice of Saunaka, surnamed Kulapati, in the forest of Naimisha",
 ' Thoseascetics, wishing to hear his wonderful narrations, presently began toaddress him who had thus arrived at that recluse abode of the inhabitantsof the forest of Naimisha',
 ' Having been entertained with due respect bythose holy men, he saluted those Munis (sages) with joined palms, evenall of them, and inquired about the progress of their asceticism',
 ' Thenall the ascetics being again seated, the son of Lomaharshana humblyoccupied the seat that was assigned to him',
 " Seeing that he wascomfortably seated, and recovered from fatigue, one of the Rishisbeginning the

In [ ]:
from transformers import BertTokenizer, BertForMaskedLM

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
inputs = tokenizer(text,return_tensors = 'pt',max_length =512,truncation=True,padding = 'max_length')

In [ ]:
inputs

{'input_ids': tensor([[  101, 18168,   999,  ...,     0,     0,     0],
        [  101,  1057, 17643,  ...,     0,     0,     0],
        [  101,  2216,  3022,  ...,     0,     0,     0],
        ...,
        [  101,  1998,  2002,  ...,     0,     0,     0],
        [  101,  1998,  1010,  ...,     0,     0,     0],
        [  101,  1005,  1000,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [ ]:
inputs['labels'] = inputs.input_ids.detach().clone()
inputs

{'input_ids': tensor([[  101, 18168,   999,  ...,     0,     0,     0],
        [  101,  1057, 17643,  ...,     0,     0,     0],
        [  101,  2216,  3022,  ...,     0,     0,     0],
        ...,
        [  101,  1998,  2002,  ...,     0,     0,     0],
        [  101,  1998,  1010,  ...,     0,     0,     0],
        [  101,  1005,  1000,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([[  101, 18168,   999,  ...,     0,     0,     0],
        [  101,  1057, 17643,  ...,     0,     0,     0],
        [  101,  2216, 

In [ ]:
rand = torch.rand(inputs.input_ids.shape)

In [ ]:
rand.shape

torch.Size([28795, 512])

In [ ]:
rand 

tensor([[0.2939, 0.6953, 0.6380,  ..., 0.0796, 0.3086, 0.7909],
        [0.3453, 0.8714, 0.1161,  ..., 0.9319, 0.7772, 0.0776],
        [0.5475, 0.6580, 0.9618,  ..., 0.9321, 0.1151, 0.9626],
        ...,
        [0.7802, 0.9171, 0.9446,  ..., 0.7929, 0.2919, 0.8484],
        [0.1017, 0.3540, 0.6299,  ..., 0.6046, 0.0947, 0.0421],
        [0.8578, 0.5524, 0.1223,  ..., 0.9987, 0.4276, 0.0083]])

In [ ]:
mask_array = (rand < 0.15)*(inputs.input_ids != 101)*(inputs.input_ids != 0)*(inputs.input_ids != 102)
mask_array

tensor([[False, False, False,  ..., False, False, False],
        [False, False,  True,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False,  True,  ..., False, False, False]])

In [ ]:
mask_array[1]

tensor([False, False,  True, False,  True, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False, False,
         True, False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,  True,
         True, False, False, False,  True, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [ ]:
labels = []
for i in range(len(mask_array)):
  labels.append(torch.flatten(mask_array[i].nonzero()).tolist())

In [ ]:
labels[:10]

[[8, 14, 24, 26, 34],
 [2, 4, 12, 16, 20, 27, 44, 53, 59, 60, 64, 68],
 [7, 11, 16, 17, 33, 36],
 [6, 20, 24, 35, 37, 41],
 [1, 6, 12, 21, 22, 25],
 [1, 9, 11, 18, 22, 25, 31, 34, 43, 44, 46, 50, 53, 57, 58],
 [4, 5, 24, 25, 27, 28, 29, 36],
 [4,
  25,
  31,
  38,
  39,
  48,
  52,
  56,
  66,
  70,
  75,
  81,
  93,
  96,
  118,
  131,
  133,
  140,
  141,
  148],
 [4, 7, 14],
 [3,
  4,
  11,
  17,
  18,
  21,
  26,
  27,
  28,
  35,
  43,
  46,
  48,
  49,
  56,
  74,
  75,
  87,
  95,
  105,
  109,
  110,
  115,
  116,
  125,
  132,
  143,
  145,
  153,
  157,
  160,
  166,
  167,
  169,
  170,
  179,
  190,
  194,
  204]]

In [ ]:
for i in range(len(mask_array)):
  inputs.input_ids[i,labels[i]] = 103

In [ ]:
inputs.input_ids

tensor([[  101, 18168,   999,  ...,     0,     0,     0],
        [  101,  1057,   103,  ...,     0,     0,     0],
        [  101,  2216,  3022,  ...,     0,     0,     0],
        ...,
        [  101,  1998,  2002,  ...,     0,     0,     0],
        [  101,  1998,  1010,  ...,     0,     0,     0],
        [  101,  1005,   103,  ...,     0,     0,     0]])

In [ ]:
class MahabharatDataset(torch.utils.data.Dataset):
  def __init__(self,encodings):
    self.encodings = encodings
  def __getitem__(self,idx):
    return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
  def __len__(self):
    return len(self.encodings.input_ids)

In [ ]:
dataset = MahabharatDataset(inputs)

In [ ]:
dataloader = torch.utils.data.DataLoader(dataset,batch_size=32,shuffle =True)

In [ ]:
# checking if you have gpu 

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [ ]:
# moving model to gpu
model.to(device)

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [ ]:
model.train()

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [ ]:
from transformers import AdamW

In [ ]:
optimizer = AdamW(model.parameters(),lr = 1e-5)

In [ ]:
torch.cuda.empty_cache()

In [ ]:
from tqdm import tqdm

epochs = 10

for epoch in range(epochs):
  loop  = tqdm(dataloader, leave = True)
  for batch in loop:
    optimizer.zero_grad()
    input_ids = batch['input_ids'].to(device)
    attention_mask= batch['attention_mask'].to(device)
    labels= batch['labels'].to(device)

    outputs = model(input_ids,attention_mask = attention_mask,labels=labels)

    loss = outputs.loss
    loss.backward()
    optimizer.step()

    loop.set_description(f'Epoch: {epoch}')
    loop.set_postfix(loss = loss.item())


  0%|          | 0/900 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """


RuntimeError: ignored